### ISSUE TITLE
add testing suite

### ISSUE THREAD

**Issue by JuanVqz** [JuanVqz/lalo_menu#1]
- [x] add [rspec](https://github.com/rspec/rspec-rails) gem and config
- [x] add [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers) gem and config
- [x] add [pry](https://github.com/pry/pry) gem and config
- [x] add [factory_bot_rails](https://github.com/thoughtbot/factory_bot_rails) gem and config
- [x] add [bullet](https://github.com/flyerhzm/bullet) gem and config
- [x] add [amazing_print](https://github.com/amazing-print/amazing_print) gem

**Comment by Ayush2020012016** [comment]
hello I want to contribute. kinda new to open source so kindly project me in correct direction.

**Comment by JuanVqz** [comment]
@Ayush2020012016 great! pick whatever you want to do just let me know in order to avoid duplicate work. Thank you!

**Comment by JuanVqz** [comment]
@Ayush2020012016 you are welcome to contribute to another issue, in fact, if you want we can have a meeting and I can show you how to fork the project, create a branch, create a PR, etc.

Keep trying to contribute an open-source project even though not on this one, +1:
